### ISSUE TITLE
unicode-math (xelatex) chargement

### ISSUE THREAD

**Issue by Briffou** [vigou3/ulthese#1]
La documentation de [unicode-math](http://ctan.math.ca/tex-archive/macros/latex/contrib/unicode-math/unicode-math.pdf) indique de le charger après les packages de l'AMS (entre autres). Autrement, certaines commandes ne fonctionnent par "correctement": typiquement $\sin$, $\cos$,.. sont en italiques au lieu d'être en mathrm. 
Mais étant donné que ulthese charge directement unicode-math, je ne vois pas comment le charger après les autres packages.

Est-ce que ce ne serait pas à l'utilisateur lui-même d'ajouter ce package dans le gabarit ? ou alors serait-il possible d'ajouter une option "nounicode-math" à la manière de "nonatbib" ?

**Comment by vigou3** [comment]
Bon point. Je n'étais pas au courant pour l'ordre de chargement. Plutôt que d'ajouter une option à la classe, je crois plus logique raisonnable de ne plus charger unicode-math par défaut. C'est, en effet, à l'utilisateur de s'en occuper.

Nous sommes sur le point de publier une nouvelle version de la classe. Je pourrai donc effectuer le changement rapidement. À moins d'avis contraire sur la direction à emprunter, je vais refuser la PR #2.

Merci pour le feedback!

**Comment by vigou3** [comment]
Par curiosité, comment avez-vous trouvé ce dépôt? Je réalise qu'il n'est mentionné nulle part dans la documentation.

**Comment by Briffou** [comment]
Ok, ça me paraît tout à fait correct de ne plus le charger par défaut.
Pour répondre à votre question, chez moi le lien Github est le 5e résultat google en tapant ulthese.
